### ISSUE TITLE
python与图数据库的连接有问题

### ISSUE THREAD

**Issue by linlin-user** [honeyandme/RAGQnASystem#6]
File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/client/__init__.py", line 806, in acquire
    cx = self._free_list.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/errors.py", line 54, in split_code
    parts = code.split(".")
AttributeError: 'NoneType' object has no attribute 'split'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hrsii/GYX/RAGQnASystem/build_up_graph.py", line 51, in <module>
    client = py2neo.Graph(args.website, user=args.user, password=args.password, name=args.dbname)
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/database.py", line 288, in __init__
    self.service = GraphService(profile, **settings)
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/database.py", line 119, in __init__
    self._connector = Connector(profile, **connector_settings)
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/client/__init__.py", line 960, in __init__
    self._add_pools(*self._initial_routers)
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/client/__init__.py", line 982, in _add_pools
    pool = ConnectionPool.open(
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/client/__init__.py", line 649, in open
    seeds = [pool.acquire() for _ in range(init_size or cls.default_init_size)]
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/client/__init__.py", line 649, in <listcomp>
    seeds = [pool.acquire() for _ in range(init_size or cls.default_init_size)]
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/client/__init__.py", line 813, in acquire
    cx = self._connect()
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/client/__init__.py", line 764, in _connect
    cx = Connection.open(self.profile, user_agent=self.user_agent,
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/client/__init__.py", line 178, in open
    return HTTP.open(profile, user_agent=user_agent,
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/client/http.py", line 63, in open
    http._hello(user_agent or http_user_agent())
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/client/http.py", line 162, in _hello
    rs.audit()
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/client/http.py", line 479, in audit
    failure = Neo4jError.hydrate(self.errors().pop(0))
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/errors.py", line 46, in hydrate
    return cls(message, code)
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/errors.py", line 64, in __new__
    classification, _, _ = cls.split_code(code)
  File "/home/hrsii/anaconda3/envs/RAGQnASystem/lib/python3.10/site-packages/py2neo/errors.py", line 56, in split_code
    raise ValueError(code)
ValueError: None

你好，该问题应该如何改正？

**Comment by chaaarlieeee** [comment]
我也遇到了这个问题

**Comment by Jack2chen** [comment]
> 我也遇到了这个问题

采用bolt方式连接 neo4j，就可以解决了，按照如下方式：
python build_up_graph.py --website bolt://localhost:7687 --user neo4j --password YourPassWord --dbname neo4j

**Comment by linlin-user** [comment]
感谢



---- 回复的原邮件 ----
| 发件人 | Jack ***@***.***> |
| 日期 | 2024年09月11日 13:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [honeyandme/RAGQnASystem] python与图数据库的连接有问题 (Issue #6) |

我也遇到了这个问题

采用bolt方式连接 neo4j，就可以解决了，按照如下方式：
python build_up_graph.py --website bolt://localhost:7687 --user neo4j --password YourPassWord --dbname neo4j
